### ISSUE TITLE
Mongo DB on Windows 10

### ISSUE THREAD

**Issue by laszewsk** [cloudmesh/cloudmesh-cloud#100]
Preferred container and linux subsystem

We want to capture multiple solutions. We only support Windows 10 
check for newest version of windows
  
a) container based           This worksonly on proper versions of windows 10, not home, e.g. edu and pro
    
b) regular install           https://docs.mongodb.com/manual/tutorial/install-mongodb-on-windows/

c) linux subsystem https://docs.microsoft.com/en-us/windows/wsl/install-win10  ubuntu 18.04

d) MOngoDB in the cloud, while making sure credentials are not in the db https://www.mongodb.com/cloud/atlas?utm_source=install-mongodb-on-windows&utm_campaign=20-docs-in-20-days&utm_medium=docs

e) Chameleon cloud or any other cloud via cloudmesh

**Comment by laszewsk** [comment]
THis is to be done in MongoDBControler.py

**Comment by AlexAxthelm** [comment]
MongoDB explicitly does not support WSL. The current solutions are bad workarounds. I would suggest not supporting Windows until a more stable solution is found.

**Comment by laszewsk** [comment]
I do not understand your comment. Lots of people run mongo an windows

**Comment by laszewsk** [comment]
https://docs.mongodb.com/v3.2/tutorial/install-mongodb-on-windows/#manually-create-a-windows-service-for-mongodb-community-edition

**Comment by laszewsk** [comment]
however we do not want to start it at boot time we want to start it explicitly. Also this could be done in a container very easily or in ubuntu subsystem

**Comment by laszewsk** [comment]
also linux subsystem is supported according to 

https://github.com/Microsoft/WSL/issues/796

furtehrmore we woudl use explicitly  mongod start and stop which seems supported. Maybe you know something we do not know, can you share concrete information that says it is not supported, have you tried it?

**Comment by AlexAxthelm** [comment]
I was referring to mongo's installation instruction page. However, if the database doesn't need to start automatically with the container, then what you have linked to looks like it should be stable enough.

**Comment by laszewsk** [comment]
see : cms admin mongo command that allows us to start and stop mongo. I have not tested if this works on windows, so this could be adapted.
In case we need an automated start, we do not do this natively, but do it in a docker container. I had at one point done this but so far we focussed on cms mongo admin start/stop commands so we can make sure that we know when mongo is running or not. THis is useful during development as we want to make sure we have thsi fine grained controll.

**Comment by laszewsk** [comment]
gregor and vafa worked on thsi and they think it works, Niranda please check
