### ISSUE TITLE
verify: Azure

### ISSUE THREAD

**Issue by laszewsk** [cloudmesh/cloudmesh-cloud#189]
verify that azure works. There could be 3 providers

AzProvider, libcloud provider, and native api provider. One of the libcloud providers is outdated and should not be used, we need to move that code into deprectaed or remove it. This is the code that we used to have in previous cloudmesh versions. 

we have started working on the AzProvider, but we are unsure about its status, as we are with the 2 other az providers

we need to make sure that pytest check the provider without database, the provider with database, and the shell command

**Comment by nirandaperera** [comment]
Closing as azure/Provider.py will only be kept and others are deprecated!
