### ISSUE TITLE
doc: azure account documentation incomplete

### ISSUE THREAD

**Issue by laszewsk** [cloudmesh/cloudmesh-cloud#195]
It is not c;early described how to obtain the infromation needed for cloudmesh yaml to use azure

**Comment by laszewsk** [comment]
have you checked the documentation in the manual on this. Is this done?

**Comment by arshadmm** [comment]
Yes, the account creation section of Azure walks through how to collect the required parameters from the azure portal. In addition, the last part of that section explicitly calls out the tenant_id, subscription_id, application_id and secret_key parameters that need to be updated in the cloudmesh.yaml file.

**Comment by laszewsk** [comment]
so its done?

**Comment by wang542** [comment]
I believe the documentation I wrote to manual solved this issue. It explicitly instructs users how to obtain and update the 4 necessary parameters in cloudmesh.yaml for azure
