### ISSUE TITLE
VM name

### ISSUE THREAD

**Issue by laszewsk** [cloudmesh/cloudmesh-cloud#22]
look at the info you get from a vm. we want to store that into mongo. We could jsut use pymongo and store everything, but we must use a unique key. We could use a unique uuid but we also want a unique name, so that may be easier.

so somehow we need to name creation scheme such as

name_schema= "{experiment}-{group}={user}-{counter}"

This can be set in 

```
class Name

   counter= n   sets and gets counter

   set (nname_schema)
   get (**kargs) named args as defined in schema
   verify(**kargs, name_schema) verifies if kargs are defined returns tru/false
   get() gets the next name and increases the counter

```

**Comment by laszewsk** [comment]
data = { "junk": "hello"}

print ("{junk}".format(**data))

**Comment by kimballXD** [comment]
@laszewsk 
I have some question about this Class.

First, is this Class only for naming vm?  Or other things that can be record by MongoDB (e.g., job) can  also get their unique name from this class? If we allow this, I will modify signature of the fucntions accordingly. Also, I think we should define default naming schema for every type of objects. 

Second, regarding `verify()`, I am not very sure what it should do. When I assigning new name, should I query mongoDB to make sure it's name haven't being used? Or just make sure the dict `kargs` has all the key-pairs that required by `schema` ?
'
Third, does this Class need to update the `counter` number when assigning new unique name?  Is the `counter` number global, or every users have their own `counter` number?

Thank you for your help.

Kimball

**Comment by laszewsk** [comment]
a) we want to make sure we have a name for vms first as this is immediatly needed.
b) later on we want this also for other types of resources. 
I am happy to entertain ideas on this but it shoudl be simple and in contrast to uuids which we will use internally also we wnat a readable name.

**Comment by laszewsk** [comment]
also see the conter proposal class in teh code

**Comment by laszewsk** [comment]
a new counter class has been developed by Gregor
