### ISSUE TITLE
Mongo: mongodb installation fails in ubuntu 

### ISSUE THREAD

**Issue by nirandaperera** [cloudmesh/cloudmesh-cloud#238]
Mongo db installation fails in Ubuntu due to sudo permission requirement and installation of curl and openssl. This needs to be remove because, installation of curl and openssl should not be a part of installing Mongo DB locally.

**Comment by laszewsk** [comment]
please implement a fix and do a pull request

**Comment by laszewsk** [comment]
to use lsb_release you need to do 

apt-get install lsb-core

before!

**Comment by laszewsk** [comment]
I assume this is fixed. can we close?

**Comment by nirandaperera** [comment]
yes
