### ISSUE TITLE
aws pem key vs ssh key

### ISSUE THREAD

**Issue by pullakhandam** [cloudmesh/cloudmesh-cloud#258]
this seems to be a bug in the specification of ssh key in cloudmesh.yaml in aws as we use 
        EC2_PRIVATE_KEY_FILE_PATH: ~/.cloudmesh/aws_cert.pem
        EC2_PRIVATE_KEY_FILE_NAME: aws_cert
it should be 
        EC2_PRIVATE_KEY_FILE_PATH: ~/.cloudmesh/
        EC2_PRIVATE_KEY_FILE_NAME: id_rsa.pub

**Comment by laszewsk** [comment]
we changed this to id_rsa
