### ISSUE TITLE
AWS: flaver vs image list 

### ISSUE THREAD

**Issue by laszewsk** [cloudmesh/cloudmesh-cloud#270]
I remember tha vaaf and i worked onbulk updates to the database form files. Is that used in teh current implementation.

**Comment by nirandaperera** [comment]
yes, it is the case. It seems like the AWS client does not have a method to get the flavor list 
https://github.com/cloudmesh/cloudmesh-cloud/blob/master/cloudmesh/compute/aws/AwsFlavors.py
