### ISSUE TITLE
Azure: Register

### ISSUE THREAD

**Issue by laszewsk** [cloudmesh/cloudmesh-cloud#274]
Please review the studnet contribution to the register command to register with azure

make sure you check the documentation and correct it.

naturally if something needs to be built in such as check if the az command is installed, please do make corrections.

**Comment by nirandaperera** [comment]
where can I find this?

**Comment by laszewsk** [comment]
examples are in oracle aws.
there is a command register i think in cloudmesh-cloud

what this is is assume you download a credential in some form form a cloud, use the file nad crete a newe entry with the credential in the cloudmesh.yaml file ...

e.g. it copies over the content, also after we have done it it deletes the original file
