### ISSUE TITLE
Azure: spelling error in _create_az_subnet_if_not_exits

### ISSUE THREAD

**Issue by laszewsk** [cloudmesh/cloudmesh-cloud#299]
this function was called 

_create_az_subnet_if_not_exitsts

please check all usages and make sure its ok

**Comment by nirandaperera** [comment]
I don't understand what the issue here is?

**Comment by laszewsk** [comment]
looking at the _az_ it may be related to the deprecated _az_ provider

**Comment by laszewsk** [comment]
This is in the current provider. The function name was changed. Locate where it is used and if it is correct, close this issue.

**Comment by nirandaperera** [comment]
oh no no. This was a method I introduced. Starting from an underscore to indicate that it is private method
